db/models.py
import asyncio
import os
import uuid

from django.conf import settings
from django.db import models
from ollama import Client
from pgvector.django import VectorField, HnswIndex

import env


ollama_client = Client(host=os.environ.get("OLLAMA_CLIENT_HOST"))


def documents_path():
    return os.path.abspath(os.path.join(settings.BASE_DIR, '../media'))


class DocumentStatusCodes(models.IntegerChoices):
    PROCESSING = 0
    READY = 1
    ERROR = 2


class DocumentTypeCodes(models.IntegerChoices):
    UNKNOWN = 0
    PDF = 1
    IMAGE = 2
    TEXT = 3


class PageStatusCodes(models.IntegerChoices):
    PROCESSING = 0
    READY = 1
    ERROR = 2


class Document(models.Model):
    id = models.CharField(max_length=50, default=uuid.uuid4, primary_key=True)
    name = models.CharField(max_length=255)
    filepath = models.FilePathField(path=documents_path)
    summary = models.TextField()
    status = models.IntegerField(choices=DocumentStatusCodes.choices,
        default=DocumentStatusCodes.PROCESSING)
    type = models.IntegerField(choices=DocumentTypeCodes.choices,
        default=DocumentTypeCodes.UNKNOWN)
    time_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-time_created']

    def __str__(self):
        return self.name


class Page(models.Model):
    document = models.ForeignKey('Document', on_delete=models.CASCADE,
        related_name='pages',)
    number = models.IntegerField()
    previous = models.OneToOneField('Page', on_delete=models.CASCADE,
        related_name='next', blank=True, null=True)
    filepath = models.FilePathField(path=documents_path, recursive=True)
    text = models.TextField(null=True, blank=True)
    text_embeddings = VectorField(dimensions=768, blank=True, null=True)
    summary = models.TextField(null=True, blank=True)
    summary_embeddings = VectorField(dimensions=768, blank=True, null=True)
    # Different from summary -- think of this as similar to alt text explaining
    # what is on the page. summary and text may be blank if the page doesn't contain
    # anything.
    description = models.TextField(null=True, blank=True)
    description_embeddings = VectorField(dimensions=768, blank=True, null=True)
    status = models.IntegerField(choices=PageStatusCodes.choices,
        default=PageStatusCodes.PROCESSING)
    error_details = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['document', 'number']
        indexes = [
            HnswIndex(
                name="text_embeddings_index",
                fields=["text_embeddings"],
                m=16,
                ef_construction=64,
                opclasses=["vector_l2_ops"],
            ),
            HnswIndex(
                name="description_embeddings_index",
                fields=["description_embeddings"],
                m=16,
                ef_construction=64,
                opclasses=["vector_l2_ops"],
            ),
            HnswIndex(
                name="summary_embeddings_index",
                fields=["summary_embeddings"],
                m=16,
                ef_construction=64,
                opclasses=["vector_l2_ops"],
            )
        ]

    def __str__(self):
        return f'{self.document.name} - {self.number}'

    def save(self, *args, **kwargs):
        # Presumably we're not going to be saving often, so OK to just
        # calculate these without checking whether the underlying text has
        # changed.
        self.text_embeddings = calculate_embeddings(self.text)
        self.summary_embeddings = calculate_embeddings(self.summary)
        self.description_embeddings = calculate_embeddings(self.description)

        super().save(*args, **kwargs)

    async def asave(self, *args, **kwargs):
        self.text_embeddings = await asyncio.to_thread(calculate_embeddings, self.text)
        self.summary_embeddings = await asyncio.to_thread(calculate_embeddings, self.summary)
        self.description_embeddings = await asyncio.to_thread(calculate_embeddings, self.description)

        await super().asave(*args, **kwargs)


class Proposition(models.Model):
    # https://arxiv.org/pdf/2312.06648
    # https://github.com/langchain-ai/langchain/blob/master/templates/propositional-retrieval/propositional_retrieval/proposal_chain.py
    # summary, start_page, end_page
    pass


class User(models.Model):
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    is_admin = models.BooleanField(default=False)


def calculate_embeddings(text):
    """Calculate 768-dimension embeddings for the given text.

    Args:
        text: str - The text to embed.

    Returns:
        TODO: Confirm Nomic returns this.
        For symmetry: https://github.com/pgvector/pgvector-python/blob/master/pgvector/django/vector.py
        np.array of np.float32
        list of float - 768-dimensions embeddings for the given text, or None if
            text is None/the empty string.
    """
    if not text:
        return None
    try:
        # This calls this:
        # https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings
        api_response = ollama_client.embed(model="nomic-embed-text", input=text)
        embeddings_list = api_response.get('embeddings')

    # TODO: Handle more specific exceptions, e.g.
    # ollama._types.ResponseError: model requires more system memory (284.9 MiB) than is available (71.0 MiB)
    except Exception as e:
        print(f"Error generating embeddings for {text}: {e}")
        return None

    # TODO: Find out if there are any non-error situation where embeddings are
    # not returned. If not, raise an error here instead of returning None.
    return embeddings_list[0] if embeddings_list else None

templates/admin.html
{% extends 'base.html' %}

{% block title %} - Admin{% endblock %}

{% block page_css %}
<style>
    body {
        height: unset;
    }
</style>
{% endblock %}

{% block content %}
<main class="admin-page">
    <form id="file-upload-form" method="POST" class="hidden">
        <h2>Upload File</h2>
        <input type="file" id="file-input" name="file" multiple>
        <button type="submit">Upload</button>
    </form>

    <div id="files-list-container">
        <div id="files-list-container-header">
            <h2>Library</h2>
            <span class="material-symbols-outlined upload-button">upload</span>
        </div>
        <div id="file-upload-queue-container" class="hidden">
            <div id="file-upload-queue-container-header">
                <h3>Upload Queue</h3>
            </div>
            <ul id="file-upload-queue">
                <!-- <li data-status="queued" data-id="">
                    <span>679.png</span>
                    <small class="file-status-indicator">Queued</small>
                    <span class="material-symbols-outlined retry-upload-button">refresh</span>
                    <span class="material-symbols-outlined remove-upload-button">cancel</span>
                </li>
                <li data-status="uploading" data-id="">
                    <span>Somefile.pdf</span>
                    <small class="file-status-indicator">Uploading</small>
                    <span class="material-symbols-outlined retry-upload-button">refresh</span>
                    <span class="material-symbols-outlined remove-upload-button">cancel</span>
                </li> -->
            </ul>
        </div>
        <ul id="file-list"></ul>
    </div>
</main>
{% endblock %}

{% block page_js %}
<script src="{{ url_for('static', filename='js/upload.js') }}"></script>
<script src="{{ url_for('static', filename='js/socket.js') }}"></script>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Wiki{% block title %} - Home{% endblock %}</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}"/>
        {% block page_css %}{% endblock %}
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li class="logo"><a href="{{ url_for('index') }}">WIKI</a></li>
                    {% if "admin" in session %}
                    <li><a href="{{ url_for('admin') }}">Admin</a></li>
                    {% endif %}
                    {% if "username" in session %}
                    <li>
                        <a href="{{ url_for('logout') }}">
                            <span class="material-symbols-outlined">logout</span>
                        </a>
                    </li>
                    {% else %}
                    {% block login_link %}<li><a href="{{ url_for('login') }}">Log In</a></li>{% endblock %}
                    {% endif %}
                </ul>
            </nav>
        </header>

        {% block content %} {% endblock %}

        <footer>
            <p>&copy; 2024. Made with <span style="color: #D91656;">&#x2665;</span> somewhere on Earth.</p>
        </footer>
        {% block page_js %}{% endblock %}
    </body>
</html>

templates/document-detail.html
{% extends 'base.html' %}

{% block title %} - {{ document.name }} {% endblock %}

{% block content %}
<main class="document-detail-page">
    <div id="document-info">
        <h2>{{ document.name }}</h2>
        <small class="document-status-indicator"> {{ document.get_status_display() }} </small>
    </div>

    <div id="page-display">
        <div id="page-metadata-container" class="tucked-away">
            <div id="page-metadata-container-toggle">
                <span class="material-symbols-outlined">info</span>
            </div>
            <div id="page-metadata">
                <h3 class="page-summary-heading">Summary</h3>
                <p class="page-summary">--</p>
                <h3 class="page-text-heading">Text</h3>
                <p class="page-text">--</p>
            </div>
        </div>
    </div>

    <div id="page-thumbnail-carousel-container">
        <div id="page-thumbnail-carousel">
            {% for page in document.pages.all() %}
            <div class="page-thumbnail" data-page-id="{{ page.id }}" data-page-number="{{ page.number }}">
                <img src="{{ url_for('serve_page_image', document_id= document.id, number=page.number) }}">
                <small class="page-number">
                {{ page.number }}
                </small>
                <small class="page-status-indicator">
                {{ page.get_status_display() }}
                </small>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}

{% block page_js %}
<script>
  const DOCUMENT_ID = "{{ document.id }}";
</script>
<script src="{{ url_for('static', filename='js/page-viewer.js') }}"></script>
{% endblock %}

templates/error.html
{% extends 'base.html' %}

{% block title %} - Error {{ status_code }} - {{ error_message }}{% endblock %}

{% block content %}
<main class="error-page">
    <h2>Error {{ status_code }}</h2>
    <p>{{ error_message }}</p>
</main>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %} - Home{% endblock %}

{% block content %}
<main class="search-page">
    <input type="text" placeholder="Type to search..." id="search" autocomplete="off"/>

    <div id="search-mode-selector-container">
        <span id="search-mode-container-header">Search Mode</span>
        <div class="radio-group">
            <label for="keyword-search-radio-button">Keyword</label>
            <input type="radio" name="mode" value="keyword" id="keyword-search-radio-button" checked>
        </div>

        <!-- TODO: Better name for this! -->
        <div id="semantic-search-group">
            <div class="radio-group">
                <label for="semantic-search-radio-button">Semantic</label>
                <input type="radio" name="mode" value="semantic" id="semantic-search-radio-button">
            </div>

            <div id="semantic-similarity-threshold-slider-container">
                <input type="range" id="semantic-similarity-threshold-slider" min="0.1" max="0.9" step="0.1">
                <span id="semantic-similarity-threshold-value">Semantic Similarity</span>
            </div>
        </div>
    </div>

    <!-- Container for search results. Hidden when empty. -->
    <div id="results-box" class="hidden"></div>
</main>
{% endblock %}

{% block page_js %}
<script src="{{ url_for('static', filename='js/search.js') }}"></script>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %} - Log In{% endblock %}
{% block login_link %}{% endblock %}
{% block content %}
<main>
    <form id="login-form" method="POST" action="{{ url_for('login') }}">
        <h2>Log In</h2>
        <input type="text" id="username-input" name="username" placeholder="username" required>
        <input type="password" id="password-input" name="password" placeholder="password" required>
        <button type="submit">Log in</button>
        {% if error_message %}
        <div class="form-error-message">{{ error_message }}</div>
        {% endif %}
    </form>
</main>
{% endblock %}